"""Alert ORM models for safety events, hardware anomalies, and zone violations."""

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import DateTime, ForeignKey, Text, Uuid, func
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.device import Device
    from app.models.student import Student
    from app.models.user import User
    from app.models.zone import Zone


class AlertType(enum.StrEnum):
    """Categorization of safety alerts triggered by ChildTrack."""

    SOS = "sos"
    FALL = "fall"
    RESTRICTED_ZONE = "restricted_zone"
    LOW_BATTERY = "low_battery"
    OFFLINE = "offline"
    LOW_CONFIDENCE = "low_confidence"
    OUT_OF_ZONE = "out_of_zone"


class AlertSeverity(enum.StrEnum):
    """Urgency level of a safety alert."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertStatus(enum.StrEnum):
    """Workflow state of an alert."""

    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"


class Alert(Base, UUIDPrimaryKeyMixin):
    """Safety and operational alert generated by ChildTrack monitoring."""

    __tablename__ = "alerts"

    student_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("students.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    device_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("devices.id", ondelete="SET NULL"),
        nullable=True,
    )
    zone_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("zones.id", ondelete="SET NULL"),
        nullable=True,
    )
    type: Mapped[AlertType] = mapped_column(
        SQLEnum(AlertType, native_enum=False),
        nullable=False,
    )
    severity: Mapped[AlertSeverity] = mapped_column(
        SQLEnum(AlertSeverity, native_enum=False),
        nullable=False,
    )
    status: Mapped[AlertStatus] = mapped_column(
        SQLEnum(AlertStatus, native_enum=False),
        default=AlertStatus.ACTIVE,
        nullable=False,
        index=True,
    )
    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )
    acknowledged_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    acknowledged_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Relationships
    student: Mapped[Optional["Student"]] = relationship("Student")
    device: Mapped[Optional["Device"]] = relationship("Device")
    zone: Mapped[Optional["Zone"]] = relationship("Zone")
    acknowledger: Mapped[Optional["User"]] = relationship("User")

    @property
    def student_name(self) -> str | None:
        if "student" in self.__dict__ and self.student:
            return self.student.full_name
        return None

    @property
    def device_code(self) -> str | None:
        if "device" in self.__dict__ and self.device:
            return self.device.device_code
        return None

    @property
    def zone_name(self) -> str | None:
        if "zone" in self.__dict__ and self.zone:
            return self.zone.name
        return None

    @property
    def acknowledger_name(self) -> str | None:
        if "acknowledger" in self.__dict__ and self.acknowledger:
            return self.acknowledger.full_name
        return None

    def __repr__(self) -> str:
        return (
            f"<Alert type={self.type.value} severity={self.severity.value} "
            f"status={self.status.value}>"
        )
