"""remove fingerprinting and add device types

Revision ID: 069cd499d9bd
Revises: 20260917_0005
Create Date: 2026-09-29 21:02:53.671147+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069cd499d9bd'
down_revision: Union[str, None] = '20260917_0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fingerprints_created_by'))
        batch_op.drop_index(batch_op.f('ix_fingerprints_status'))
        batch_op.drop_index(batch_op.f('ix_fingerprints_zone_id'))

    op.drop_table('fingerprints')
    with op.batch_alter_table('fingerprint_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fingerprint_samples_access_point_id'))
        batch_op.drop_index(batch_op.f('ix_fingerprint_samples_fingerprint_id'))

    op.drop_table('fingerprint_samples')
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_points_bssid'))

    op.drop_table('access_points')
    with op.batch_alter_table('fingerprint_ap_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fingerprint_ap_stats_access_point_id'))
        batch_op.drop_index(batch_op.f('ix_fingerprint_ap_stats_fingerprint_id'))

    op.drop_table('fingerprint_ap_stats')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('WEARABLE', 'SCANNER', name='device_type', native_enum=False), nullable=False, server_default=sa.text("'wearable'")))
        batch_op.add_column(sa.Column('assigned_zone_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_devices_assigned_zone_id_zones'), 'zones', ['assigned_zone_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_devices_assigned_zone_id_zones'), type_='foreignkey')
        batch_op.drop_column('assigned_zone_id')
        batch_op.drop_column('type')

    op.create_table('fingerprint_ap_stats',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('fingerprint_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('access_point_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('median_rssi', sa.FLOAT(), nullable=False),
    sa.Column('mean_rssi', sa.FLOAT(), nullable=False),
    sa.Column('stddev_rssi', sa.FLOAT(), nullable=False),
    sa.Column('sample_count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], name=op.f('fk_fingerprint_ap_stats_access_point_id_access_points'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fingerprint_id'], ['fingerprints.id'], name=op.f('fk_fingerprint_ap_stats_fingerprint_id_fingerprints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fingerprint_ap_stats'))
    )
    with op.batch_alter_table('fingerprint_ap_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fingerprint_ap_stats_fingerprint_id'), ['fingerprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fingerprint_ap_stats_access_point_id'), ['access_point_id'], unique=False)

    op.create_table('access_points',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('bssid', sa.VARCHAR(length=17), nullable=False),
    sa.Column('channel', sa.INTEGER(), nullable=True),
    sa.Column('zone_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_access_points_zone_id_zones'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_points'))
    )
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_points_bssid'), ['bssid'], unique=1)

    op.create_table('fingerprint_samples',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('fingerprint_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('access_point_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('rssi', sa.INTEGER(), nullable=False),
    sa.Column('collected_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], name=op.f('fk_fingerprint_samples_access_point_id_access_points'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fingerprint_id'], ['fingerprints.id'], name=op.f('fk_fingerprint_samples_fingerprint_id_fingerprints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fingerprint_samples'))
    )
    with op.batch_alter_table('fingerprint_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fingerprint_samples_fingerprint_id'), ['fingerprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fingerprint_samples_access_point_id'), ['access_point_id'], unique=False)

    op.create_table('fingerprints',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('zone_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=False),
    sa.Column('sample_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('quality_score', sa.FLOAT(), nullable=True),
    sa.Column('min_rssi_cutoff', sa.INTEGER(), server_default=sa.text("'-85'"), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_fingerprints_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_fingerprints_zone_id_zones'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fingerprints'))
    )
    with op.batch_alter_table('fingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fingerprints_zone_id'), ['zone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fingerprints_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fingerprints_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###
